/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

/**
 *
 * @author BalbalPC
 */
public class lamanTigaOto extends javax.swing.JFrame {

    /**
     * Creates new form lamanTiga
     */
    public lamanTigaOto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalOto = new javax.swing.JButton();
        tfTotalOto = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deskMb = new javax.swing.JButton();
        hijauMob = new javax.swing.JRadioButton();
        merahMob = new javax.swing.JRadioButton();
        kuningMob = new javax.swing.JRadioButton();
        biruMob = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jumMobBir = new javax.swing.JSpinner();
        hargaMob = new javax.swing.JTextField();
        jumMobKun = new javax.swing.JSpinner();
        jumMobHij = new javax.swing.JSpinner();
        jumMobMer = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        deskBec = new javax.swing.JButton();
        hijauBec = new javax.swing.JRadioButton();
        merahBec = new javax.swing.JRadioButton();
        kuningBec = new javax.swing.JRadioButton();
        biruBec = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jumBecBir = new javax.swing.JSpinner();
        hargaBec = new javax.swing.JTextField();
        jumBecKun = new javax.swing.JSpinner();
        jumBecHij = new javax.swing.JSpinner();
        jumBecMer = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        deskMot = new javax.swing.JButton();
        hijauMot = new javax.swing.JRadioButton();
        merahMot = new javax.swing.JRadioButton();
        kuningMot = new javax.swing.JRadioButton();
        biruMot = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jumMotBir = new javax.swing.JSpinner();
        hargaMot = new javax.swing.JTextField();
        jumMotKun = new javax.swing.JSpinner();
        jumMotHij = new javax.swing.JSpinner();
        jumMotMer = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hai, Selamat Datang");

        totalOto.setText("Total harga");
        totalOto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalOtoActionPerformed(evt);
            }
        });

        tfTotalOto.setEditable(false);
        tfTotalOto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalOtoActionPerformed(evt);
            }
        });

        nama.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalOto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalOto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalOto)
                        .addComponent(tfTotalOto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nama)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("mobil");

        deskMb.setText("Lihat deskripsi");
        deskMb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskMbActionPerformed(evt);
            }
        });

        hijauMob.setText("hijau");
        hijauMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauMobActionPerformed(evt);
            }
        });

        merahMob.setText("merah");
        merahMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahMobActionPerformed(evt);
            }
        });

        kuningMob.setText("kuning");
        kuningMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningMobActionPerformed(evt);
            }
        });

        biruMob.setText("biru");
        biruMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruMobActionPerformed(evt);
            }
        });

        jLabel19.setText("varian");

        hargaMob.setEditable(false);
        hargaMob.setText("Rp. 70.000.000");
        hargaMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaMobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskMb, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahMob, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMobMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauMob, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMobHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningMob, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMobKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumMobBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruMob, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahMob, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauMob, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningMob, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruMob, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskMb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMobBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMobKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMobHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMobMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("becak");

        deskBec.setText("Lihat deskripsi");
        deskBec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskBecActionPerformed(evt);
            }
        });

        hijauBec.setText("hijau");
        hijauBec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauBecActionPerformed(evt);
            }
        });

        merahBec.setText("merah");
        merahBec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahBecActionPerformed(evt);
            }
        });

        kuningBec.setText("kuning");
        kuningBec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningBecActionPerformed(evt);
            }
        });

        biruBec.setText("biru");
        biruBec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruBecActionPerformed(evt);
            }
        });

        jLabel30.setText("varian");

        hargaBec.setEditable(false);
        hargaBec.setText("Rp. 1.005.000");
        hargaBec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaBecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskBec, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel30)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahBec, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBecMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauBec, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBecHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningBec, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBecKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumBecBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruBec, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaBec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaBec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahBec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauBec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningBec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruBec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskBec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBecBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBecKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBecHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBecMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("motor");

        deskMot.setText("Lihat deskripsi");
        deskMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskMotActionPerformed(evt);
            }
        });

        hijauMot.setText("hijau");
        hijauMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauMotActionPerformed(evt);
            }
        });

        merahMot.setText("merah");
        merahMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahMotActionPerformed(evt);
            }
        });

        kuningMot.setText("kuning");
        kuningMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningMotActionPerformed(evt);
            }
        });

        biruMot.setText("biru");
        biruMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruMotActionPerformed(evt);
            }
        });

        jLabel31.setText("varian");

        hargaMot.setEditable(false);
        hargaMot.setText("Rp. 11.650.000");
        hargaMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaMotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskMot, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel31)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahMot, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMotMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauMot, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMotHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningMot, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMotKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumMotBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruMot, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaMot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaMot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahMot, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauMot, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningMot, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruMot, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskMot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMotBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMotKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMotHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMotMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deskMbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskMbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskMbActionPerformed

    private void hargaMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaMobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaMobActionPerformed

    private void deskBecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskBecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskBecActionPerformed

    private void hargaBecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaBecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBecActionPerformed

    private void deskMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskMotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskMotActionPerformed

    private void hargaMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaMotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaMotActionPerformed

    private void merahMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahMobActionPerformed
        // TODO add your handling code here:
        if(merahMob.isSelected()){
            hargaMob.setText("Rp. 70.000.000");
            hijauMob.setEnabled(false);
            kuningMob.setEnabled(false);
            biruMob.setEnabled(false);
        }else{
            hijauMob.setEnabled(true);
            kuningMob.setEnabled(true);
            biruMob.setEnabled(true);
        }
    }//GEN-LAST:event_merahMobActionPerformed

    private void totalOtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalOtoActionPerformed
        // TODO add your handling code here:
        int totMerahMob = 70000000 * (int)jumMobMer.getValue();
        int totHijauMob = 80000000 * (int)jumMobHij.getValue();
        int totKuningMob = 90000000 * (int)jumMobKun.getValue();
        int totBiruMob = 100000000 * (int)jumMobBir.getValue();
        
        int totMerahMot = 11650000 * (int)jumMotMer.getValue();
        int totHijauMot = 12650000 * (int)jumMotHij.getValue();
        int totKuningMot = 13650000 * (int)jumMotKun.getValue();
        int totBiruMot = 14650000 * (int)jumMotBir.getValue();
        
        int totMerahBec = 1005000 * (int)jumBecMer.getValue();
        int totHijauBec = 2005000 * (int)jumBecHij.getValue();
        int totKuningBec = 3005000 * (int)jumBecKun.getValue();
        int totBiruBec = 4005000 * (int)jumBecBir.getValue();
        
        int total = totMerahMob + totHijauMob + totKuningMob + totBiruMob + totMerahMot + totHijauMot + totKuningMot + totBiruMot + totMerahBec + totHijauBec + totKuningBec + totBiruBec;
        
        tfTotalOto.setText(Integer.toString(total));
    }//GEN-LAST:event_totalOtoActionPerformed

    private void hijauMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauMobActionPerformed
        // TODO add your handling code here:
        if(hijauMob.isSelected()){
            hargaMob.setText("Rp. 80.000.000");
            merahMob.setEnabled(false);
            kuningMob.setEnabled(false);
            biruMob.setEnabled(false);
        }else{
            merahMob.setEnabled(true);
            kuningMob.setEnabled(true);
            biruMob.setEnabled(true);
        }
    }//GEN-LAST:event_hijauMobActionPerformed

    private void kuningMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningMobActionPerformed
        // TODO add your handling code here:
        if(kuningMob.isSelected()){
            hargaMob.setText("Rp. 90.000.000");
            merahMob.setEnabled(false);
            hijauMob.setEnabled(false);
            biruMob.setEnabled(false);
        }else{
            merahMob.setEnabled(true);
            hijauMob.setEnabled(true);
            biruMob.setEnabled(true);
        }

    }//GEN-LAST:event_kuningMobActionPerformed

    private void biruMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruMobActionPerformed
        // TODO add your handling code here:
        if(biruMob.isSelected()){
            hargaMob.setText("Rp. 100.000.000");
            merahMob.setEnabled(false);
            hijauMob.setEnabled(false);
            kuningMob.setEnabled(false);
        }else{
            merahMob.setEnabled(true);
            hijauMob.setEnabled(true);
            kuningMob.setEnabled(true);
        }
    }//GEN-LAST:event_biruMobActionPerformed

    private void merahMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahMotActionPerformed
        // TODO add your handling code here:
        if(merahMot.isSelected()){
            hargaMot.setText("Rp. 11.165.000");
            hijauMot.setEnabled(false);
            kuningMot.setEnabled(false);
            biruMot.setEnabled(false);
        }else{
            hijauMot.setEnabled(true);
            kuningMot.setEnabled(true);
            biruMot.setEnabled(true);
        }
    }//GEN-LAST:event_merahMotActionPerformed

    private void hijauMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauMotActionPerformed
        // TODO add your handling code here:
        if(hijauMot.isSelected()){
            hargaMot.setText("Rp. 12.650.000");
            merahMot.setEnabled(false);
            kuningMot.setEnabled(false);
            biruMot.setEnabled(false);
        }else{
            merahMot.setEnabled(true);
            kuningMot.setEnabled(true);
            biruMot.setEnabled(true);
        }
    }//GEN-LAST:event_hijauMotActionPerformed

    private void kuningMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningMotActionPerformed
        // TODO add your handling code here:
        if(kuningMot.isSelected()){
            hargaMot.setText("Rp. 13.650.000");
            merahMot.setEnabled(false);
            hijauMot.setEnabled(false);
            biruMot.setEnabled(false);
        }else{
            merahMot.setEnabled(true);
            hijauMot.setEnabled(true);
            biruMot.setEnabled(true);
        }
    }//GEN-LAST:event_kuningMotActionPerformed

    private void biruMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruMotActionPerformed
        // TODO add your handling code here:
        if(biruMot.isSelected()){
            hargaMot.setText("Rp. 14.650.000");
            merahMot.setEnabled(false);
            hijauMot.setEnabled(false);
            kuningMot.setEnabled(false);
        }else{
            merahMot.setEnabled(true);
            hijauMot.setEnabled(true);
            kuningMot.setEnabled(true);
        }
    }//GEN-LAST:event_biruMotActionPerformed

    private void merahBecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahBecActionPerformed
        // TODO add your handling code here:
        if(merahBec.isSelected()){
            hargaBec.setText("Rp. 1.005.000");
            hijauBec.setEnabled(false);
            kuningBec.setEnabled(false);
            biruBec.setEnabled(false);
        }else{
            hijauBec.setEnabled(true);
            kuningBec.setEnabled(true);
            biruBec.setEnabled(true);
        }
    }//GEN-LAST:event_merahBecActionPerformed

    private void hijauBecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauBecActionPerformed
        // TODO add your handling code here:
        if(hijauBec.isSelected()){
            hargaBec.setText("Rp. 2.005.000");
            merahBec.setEnabled(false);
            kuningBec.setEnabled(false);
            biruBec.setEnabled(false);
        }else{
            merahBec.setEnabled(true);
            kuningBec.setEnabled(true);
            biruBec.setEnabled(true);
        }
    }//GEN-LAST:event_hijauBecActionPerformed

    private void kuningBecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningBecActionPerformed
        // TODO add your handling code here:
        if(kuningBec.isSelected()){
            hargaBec.setText("Rp. 3.005.000");
            merahBec.setEnabled(false);
            hijauBec.setEnabled(false);
            biruBec.setEnabled(false);
        }else{
            merahBec.setEnabled(true);
            hijauBec.setEnabled(true);
            biruBec.setEnabled(true);
        }
    }//GEN-LAST:event_kuningBecActionPerformed

    private void biruBecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruBecActionPerformed
        // TODO add your handling code here:
        if(biruBec.isSelected()){
            hargaBec.setText("Rp. 4.005.000");
            merahBec.setEnabled(false);
            hijauBec.setEnabled(false);
            kuningBec.setEnabled(false);
        }else{
            merahBec.setEnabled(true);
            hijauBec.setEnabled(true);
            kuningBec.setEnabled(true);
        }
    }//GEN-LAST:event_biruBecActionPerformed

    private void tfTotalOtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalOtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalOtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lamanTigaOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lamanTigaOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lamanTigaOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lamanTigaOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lamanTigaOto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton biruBec;
    private javax.swing.JRadioButton biruMob;
    private javax.swing.JRadioButton biruMot;
    private javax.swing.JButton deskBec;
    private javax.swing.JButton deskMb;
    private javax.swing.JButton deskMot;
    private javax.swing.JTextField hargaBec;
    private javax.swing.JTextField hargaMob;
    private javax.swing.JTextField hargaMot;
    private javax.swing.JRadioButton hijauBec;
    private javax.swing.JRadioButton hijauMob;
    private javax.swing.JRadioButton hijauMot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jumBecBir;
    private javax.swing.JSpinner jumBecHij;
    private javax.swing.JSpinner jumBecKun;
    private javax.swing.JSpinner jumBecMer;
    private javax.swing.JSpinner jumMobBir;
    private javax.swing.JSpinner jumMobHij;
    private javax.swing.JSpinner jumMobKun;
    private javax.swing.JSpinner jumMobMer;
    private javax.swing.JSpinner jumMotBir;
    private javax.swing.JSpinner jumMotHij;
    private javax.swing.JSpinner jumMotKun;
    private javax.swing.JSpinner jumMotMer;
    private javax.swing.JRadioButton kuningBec;
    private javax.swing.JRadioButton kuningMob;
    private javax.swing.JRadioButton kuningMot;
    private javax.swing.JRadioButton merahBec;
    private javax.swing.JRadioButton merahMob;
    private javax.swing.JRadioButton merahMot;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField tfTotalOto;
    private javax.swing.JButton totalOto;
    // End of variables declaration//GEN-END:variables
    void nama(String nama1){
        nama.setText(nama1);
    }
}
