/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

/**
 *
 * @author BalbalPC
 */
public class lamanTigaMak extends javax.swing.JFrame {
    total a = new total();
    /**
     * Creates new form lamanTiga
     */
    public lamanTigaMak() {
        initComponents();
        totalBayar.setText(Integer.toString(a.getInvoice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalGul = new javax.swing.JButton();
        tfTotalMak = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();
        totalBayar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deskSos = new javax.swing.JButton();
        hijauSos = new javax.swing.JRadioButton();
        merahSos = new javax.swing.JRadioButton();
        kuningSos = new javax.swing.JRadioButton();
        biruSos = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jumSosBir = new javax.swing.JSpinner();
        hargaSos = new javax.swing.JTextField();
        jumSosKun = new javax.swing.JSpinner();
        jumSosHij = new javax.swing.JSpinner();
        jumSosMer = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        deskGul = new javax.swing.JButton();
        hijauGul = new javax.swing.JRadioButton();
        merahGul = new javax.swing.JRadioButton();
        kuningGul = new javax.swing.JRadioButton();
        biruGul = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jumlahGulBir = new javax.swing.JSpinner();
        hargaGul = new javax.swing.JTextField();
        jumlahGulKun = new javax.swing.JSpinner();
        jumlahGulHij = new javax.swing.JSpinner();
        jumlahGulMer = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        deskTel = new javax.swing.JButton();
        hijauKTel = new javax.swing.JRadioButton();
        merahKTel = new javax.swing.JRadioButton();
        kuningTel = new javax.swing.JRadioButton();
        biruTel = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jumlahTelBir = new javax.swing.JSpinner();
        hargaTel = new javax.swing.JTextField();
        jumlahTelKun = new javax.swing.JSpinner();
        jumlahTelHij = new javax.swing.JSpinner();
        jumlahTelMer = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hai, Selamat Datang");

        totalGul.setText("Total harga");
        totalGul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalGulActionPerformed(evt);
            }
        });

        tfTotalMak.setEditable(false);
        tfTotalMak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalMakActionPerformed(evt);
            }
        });

        nama.setText("jLabel2");

        bayar.setText("bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        totalBayar.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama)
                .addGap(18, 18, 18)
                .addComponent(bayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalGul)
                .addGap(18, 18, 18)
                .addComponent(tfTotalMak, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalGul)
                        .addComponent(tfTotalMak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nama)
                        .addComponent(bayar)
                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Sosis");

        deskSos.setText("Lihat deskripsi");
        deskSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskSosActionPerformed(evt);
            }
        });

        hijauSos.setText("hijau");
        hijauSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauSosActionPerformed(evt);
            }
        });

        merahSos.setText("merah");
        merahSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahSosActionPerformed(evt);
            }
        });

        kuningSos.setText("kuning");
        kuningSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningSosActionPerformed(evt);
            }
        });

        biruSos.setText("biru");
        biruSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruSosActionPerformed(evt);
            }
        });

        jLabel19.setText("varian");

        hargaSos.setEditable(false);
        hargaSos.setText("Rp. 7.000");
        hargaSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaSosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskSos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahSos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumSosMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauSos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumSosHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningSos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumSosKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumSosBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruSos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahSos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauSos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningSos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruSos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskSos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumSosBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumSosKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumSosHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumSosMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Gula");

        deskGul.setText("Lihat deskripsi");
        deskGul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskGulActionPerformed(evt);
            }
        });

        hijauGul.setText("hijau");
        hijauGul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauGulActionPerformed(evt);
            }
        });

        merahGul.setText("merah");
        merahGul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahGulActionPerformed(evt);
            }
        });

        kuningGul.setText("kuning");
        kuningGul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningGulActionPerformed(evt);
            }
        });

        biruGul.setText("biru");
        biruGul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruGulActionPerformed(evt);
            }
        });

        jLabel30.setText("varian");

        hargaGul.setEditable(false);
        hargaGul.setText("Rp. 17.000");
        hargaGul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaGulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskGul, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel30)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahGul, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahGulMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauGul, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahGulHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningGul, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahGulKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahGulBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruGul, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaGul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaGul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahGul, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauGul, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningGul, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruGul, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskGul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahGulBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahGulKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahGulHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahGulMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Telur");

        deskTel.setText("Lihat deskripsi");
        deskTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskTelActionPerformed(evt);
            }
        });

        hijauKTel.setText("hijau");
        hijauKTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauKTelActionPerformed(evt);
            }
        });

        merahKTel.setText("merah");
        merahKTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahKTelActionPerformed(evt);
            }
        });

        kuningTel.setText("kuning");
        kuningTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningTelActionPerformed(evt);
            }
        });

        biruTel.setText("biru");
        biruTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruTelActionPerformed(evt);
            }
        });

        jLabel31.setText("varian");

        hargaTel.setEditable(false);
        hargaTel.setText("Rp. 16.500");
        hargaTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskTel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel31)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahKTel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahTelMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauKTel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahTelHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningTel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahTelKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahTelBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruTel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahKTel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauKTel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningTel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruTel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskTel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahTelBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahTelKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahTelHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahTelMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deskSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskSosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskSosActionPerformed

    private void hargaSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaSosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaSosActionPerformed

    private void deskGulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskGulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskGulActionPerformed

    private void hargaGulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaGulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaGulActionPerformed

    private void deskTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskTelActionPerformed

    private void hargaTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTelActionPerformed

    private void totalGulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalGulActionPerformed
        // TODO add your handling code here:
        int totMerahSos = 7000 * (int)jumSosMer.getValue();
        int totHijauSos = 7500 * (int)jumSosHij.getValue();
        int totKuningSos = 10000 * (int)jumSosKun.getValue();
        int totBiruSos = 6000 * (int)jumSosBir.getValue();
        
        int totMerahTel = 16000 * (int)jumlahTelMer.getValue();
        int totHijauTel = 17000 * (int)jumlahTelHij.getValue();
        int totKuningTel = 1700 * (int)jumlahTelKun.getValue();
        int totBiruTel = 6000 * (int)jumlahTelBir.getValue();
        
        int totMerahGul = 17000 * (int)jumlahGulMer.getValue();
        int totHijauGul = 10000 * (int)jumlahGulHij.getValue();
        int totKuningGul = 19000 * (int)jumlahGulKun.getValue();
        int totBiruGul = 16000 * (int)jumlahGulBir.getValue();
        
        int total = totMerahSos + totHijauSos + totKuningSos + totBiruSos + totMerahTel + totHijauTel + totKuningTel + totBiruTel + totMerahGul + totHijauGul + totKuningGul + totBiruGul;
        a.setInvoice(total);
        totalBayar.setText(Integer.toString(a.getInvoice()));
        tfTotalMak.setText(Integer.toString(total));
        
    }//GEN-LAST:event_totalGulActionPerformed

    private void merahGulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahGulActionPerformed
        // TODO add your handling code here:
        if(merahGul.isSelected()){
            hargaGul.setText("Rp. 17.000");
            hijauGul.setEnabled(false);
            kuningGul.setEnabled(false);
            biruGul.setEnabled(false);
        }else{
            hijauGul.setEnabled(true);
            kuningGul.setEnabled(true);
            biruGul.setEnabled(true);
        }
    }//GEN-LAST:event_merahGulActionPerformed

    private void merahSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahSosActionPerformed
        // TODO add your handling code here:
        if(merahSos.isSelected()){
            hargaSos.setText("Rp. 7.000");
            hijauSos.setEnabled(false);
            kuningSos.setEnabled(false);
            biruSos.setEnabled(false);
        }else{
            hijauSos.setEnabled(true);
            kuningSos.setEnabled(true);
            biruSos.setEnabled(true);
        }
    }//GEN-LAST:event_merahSosActionPerformed

    private void tfTotalMakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalMakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalMakActionPerformed

    private void kuningSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningSosActionPerformed
        // TODO add your handling code here:if(kuningLip.isSelected()){
        if(kuningSos.isSelected()){
            hargaSos.setText("Rp. 7500");
            merahSos.setEnabled(false);
            hijauSos.setEnabled(false);
            biruSos.setEnabled(false);
        }else{
            merahSos.setEnabled(true);
            hijauSos.setEnabled(true);
            biruSos.setEnabled(true);
        }
    }//GEN-LAST:event_kuningSosActionPerformed

    private void hijauSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauSosActionPerformed
        // TODO add your handling code here:
        if(hijauSos.isSelected()){
            hargaSos.setText("Rp. 10.000");
            merahSos.setEnabled(false);
            kuningSos.setEnabled(false);
            biruSos.setEnabled(false);
        }else{
            merahSos.setEnabled(true);
            kuningSos.setEnabled(true);
            biruSos.setEnabled(true);
        }
    }//GEN-LAST:event_hijauSosActionPerformed

    private void biruSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruSosActionPerformed
        // TODO add your handling code here:
        if(biruSos.isSelected()){
            hargaSos.setText("Rp. 6.000");
            merahSos.setEnabled(false);
            hijauSos.setEnabled(false);
            kuningSos.setEnabled(false);
        }else{
            merahSos.setEnabled(true);
            hijauSos.setEnabled(true);
            kuningSos.setEnabled(true);
        }
    }//GEN-LAST:event_biruSosActionPerformed

    private void merahKTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahKTelActionPerformed
        // TODO add your handling code here:
        if(merahKTel.isSelected()){
            hargaTel.setText("Rp. 16.500");
            hijauKTel.setEnabled(false);
            kuningTel.setEnabled(false);
            biruTel.setEnabled(false);
        }else{
            hijauKTel.setEnabled(true);
            kuningTel.setEnabled(true);
            biruTel.setEnabled(true);
        }
    }//GEN-LAST:event_merahKTelActionPerformed

    private void hijauKTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauKTelActionPerformed
        // TODO add your handling code here:
        if(hijauKTel.isSelected()){
            hargaTel.setText("Rp. 17.000");
            merahKTel.setEnabled(false);
            kuningTel.setEnabled(false);
            biruTel.setEnabled(false);
        }else{
            merahKTel.setEnabled(true);
            kuningTel.setEnabled(true);
            biruTel.setEnabled(true);
        }
    }//GEN-LAST:event_hijauKTelActionPerformed

    private void kuningTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningTelActionPerformed
        // TODO add your handling code here:
        if(kuningTel.isSelected()){
            hargaTel.setText("Rp. 1700");
            merahKTel.setEnabled(false);
            hijauKTel.setEnabled(false);
            biruTel.setEnabled(false);
        }else{
            merahKTel.setEnabled(true);
            hijauKTel.setEnabled(true);
            biruTel.setEnabled(true);
        }
    }//GEN-LAST:event_kuningTelActionPerformed

    private void biruTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruTelActionPerformed
        // TODO add your handling code here:
         if(biruTel.isSelected()){
            hargaTel.setText("Rp. 6.000");
            merahKTel.setEnabled(false);
            hijauKTel.setEnabled(false);
            kuningTel.setEnabled(false);
        }else{
            merahKTel.setEnabled(true);
            hijauKTel.setEnabled(true);
            kuningTel.setEnabled(true);
        }
    }//GEN-LAST:event_biruTelActionPerformed

    private void biruGulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruGulActionPerformed
        // TODO add your handling code here:
         if(biruGul.isSelected()){
            hargaGul.setText("Rp. 16.000");
            merahGul.setEnabled(false);
            hijauGul.setEnabled(false);
            kuningGul.setEnabled(false);
        }else{
            merahSos.setEnabled(true);
            hijauSos.setEnabled(true);
            kuningSos.setEnabled(true);
        }
    }//GEN-LAST:event_biruGulActionPerformed

    private void kuningGulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningGulActionPerformed
        // TODO add your handling code here:
        if(kuningGul.isSelected()){
            hargaGul.setText("Rp. 19000");
            merahGul.setEnabled(false);
            hijauGul.setEnabled(false);
            biruGul.setEnabled(false);
        }else{
            merahGul.setEnabled(true);
            hijauGul.setEnabled(true);
            biruGul.setEnabled(true);
        }
    }//GEN-LAST:event_kuningGulActionPerformed

    private void hijauGulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauGulActionPerformed
        // TODO add your handling code here:
        if(hijauGul.isSelected()){
            hargaGul.setText("Rp. 10.000");
            merahGul.setEnabled(false);
            kuningGul.setEnabled(false);
            biruGul.setEnabled(false);
        }else{
            merahGul.setEnabled(true);
            kuningGul.setEnabled(true);
            biruGul.setEnabled(true);
        }
    }//GEN-LAST:event_hijauGulActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
        totalBayar.setText(Integer.toString(a.getInvoice()));
    }//GEN-LAST:event_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lamanTigaMak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lamanTigaMak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lamanTigaMak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lamanTigaMak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lamanTigaMak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayar;
    private javax.swing.JRadioButton biruGul;
    private javax.swing.JRadioButton biruSos;
    private javax.swing.JRadioButton biruTel;
    private javax.swing.JButton deskGul;
    private javax.swing.JButton deskSos;
    private javax.swing.JButton deskTel;
    private javax.swing.JTextField hargaGul;
    private javax.swing.JTextField hargaSos;
    private javax.swing.JTextField hargaTel;
    private javax.swing.JRadioButton hijauGul;
    private javax.swing.JRadioButton hijauKTel;
    private javax.swing.JRadioButton hijauSos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jumSosBir;
    private javax.swing.JSpinner jumSosHij;
    private javax.swing.JSpinner jumSosKun;
    private javax.swing.JSpinner jumSosMer;
    private javax.swing.JSpinner jumlahGulBir;
    private javax.swing.JSpinner jumlahGulHij;
    private javax.swing.JSpinner jumlahGulKun;
    private javax.swing.JSpinner jumlahGulMer;
    private javax.swing.JSpinner jumlahTelBir;
    private javax.swing.JSpinner jumlahTelHij;
    private javax.swing.JSpinner jumlahTelKun;
    private javax.swing.JSpinner jumlahTelMer;
    private javax.swing.JRadioButton kuningGul;
    private javax.swing.JRadioButton kuningSos;
    private javax.swing.JRadioButton kuningTel;
    private javax.swing.JRadioButton merahGul;
    private javax.swing.JRadioButton merahKTel;
    private javax.swing.JRadioButton merahSos;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField tfTotalMak;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JButton totalGul;
    // End of variables declaration//GEN-END:variables
    void nama(String nama1){
        nama.setText(nama1);
    }
    void totalHar(int harga1){
        totalBayar.setText(Integer.toString(harga1));
    }
}
