/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import javax.swing.JOptionPane;
/**
 *
 * @author BalbalPC
 */
public class lamanTigaTek extends javax.swing.JFrame {
    total a = new total();
        private lamanInvoice b;
    /**
     * Creates new form lamanTiga
     */
    public lamanTigaTek() {
        initComponents();
                b = new lamanInvoice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalTek = new javax.swing.JButton();
        tfTotalTek = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();
        totalBayar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deskLap = new javax.swing.JButton();
        hijauLap = new javax.swing.JRadioButton();
        merahLap = new javax.swing.JRadioButton();
        kuningLap = new javax.swing.JRadioButton();
        biruLap = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jumLapBir = new javax.swing.JSpinner();
        hargaLap = new javax.swing.JTextField();
        jumLapKun = new javax.swing.JSpinner();
        jumLapHij = new javax.swing.JSpinner();
        jumLapMer = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        deskHan = new javax.swing.JButton();
        hijauHan = new javax.swing.JRadioButton();
        merahHan = new javax.swing.JRadioButton();
        kuningHan = new javax.swing.JRadioButton();
        biruHan = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jumHanBir = new javax.swing.JSpinner();
        hargaHan = new javax.swing.JTextField();
        jumHanKun = new javax.swing.JSpinner();
        jumHanHij = new javax.swing.JSpinner();
        jumHanMer = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        deskKomp = new javax.swing.JButton();
        hijauKomp = new javax.swing.JRadioButton();
        merahKomp = new javax.swing.JRadioButton();
        kuningKomp = new javax.swing.JRadioButton();
        biruKomp = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jumKompBir = new javax.swing.JSpinner();
        hargaKomp = new javax.swing.JTextField();
        jumKompKun = new javax.swing.JSpinner();
        jumKompHij = new javax.swing.JSpinner();
        jumKompMer = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hai, Selamat Datang");

        totalTek.setText("total harga");
        totalTek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTekActionPerformed(evt);
            }
        });

        tfTotalTek.setEditable(false);

        nama.setText("jLabel2");

        bayar.setText("bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        totalBayar.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalTek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalTek, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalTek)
                        .addComponent(tfTotalTek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nama)
                        .addComponent(bayar)
                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Laptop");

        deskLap.setText("Lihat deskripsi");
        deskLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskLapActionPerformed(evt);
            }
        });

        hijauLap.setText("hijau");
        hijauLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauLapActionPerformed(evt);
            }
        });

        merahLap.setText("merah");
        merahLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahLapActionPerformed(evt);
            }
        });

        kuningLap.setText("kuning");
        kuningLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningLapActionPerformed(evt);
            }
        });

        biruLap.setText("biru");
        biruLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruLapActionPerformed(evt);
            }
        });

        jLabel19.setText("varian");

        hargaLap.setEditable(false);
        hargaLap.setText("Rp. 7.000.000");
        hargaLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaLapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskLap, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahLap, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumLapMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauLap, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumLapHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningLap, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumLapKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumLapBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruLap, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahLap, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauLap, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningLap, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruLap, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskLap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumLapBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumLapKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumLapHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumLapMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("handphone");

        deskHan.setText("Lihat deskripsi");
        deskHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskHanActionPerformed(evt);
            }
        });

        hijauHan.setText("hijau");
        hijauHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauHanActionPerformed(evt);
            }
        });

        merahHan.setText("merah");
        merahHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahHanActionPerformed(evt);
            }
        });

        kuningHan.setText("kuning");
        kuningHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningHanActionPerformed(evt);
            }
        });

        biruHan.setText("biru");
        biruHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruHanActionPerformed(evt);
            }
        });

        jLabel30.setText("varian");

        hargaHan.setEditable(false);
        hargaHan.setText("Rp. 1.005.000");
        hargaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaHanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskHan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel30)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahHan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumHanMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauHan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumHanHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningHan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumHanKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumHanBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruHan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahHan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauHan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningHan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruHan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskHan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumHanBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumHanKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumHanHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumHanMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Komputer");

        deskKomp.setText("Lihat deskripsi");
        deskKomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskKompActionPerformed(evt);
            }
        });

        hijauKomp.setText("hijau");
        hijauKomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauKompActionPerformed(evt);
            }
        });

        merahKomp.setText("merah");
        merahKomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahKompActionPerformed(evt);
            }
        });

        kuningKomp.setText("kuning");
        kuningKomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningKompActionPerformed(evt);
            }
        });

        biruKomp.setText("biru");
        biruKomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruKompActionPerformed(evt);
            }
        });

        jLabel31.setText("varian");

        hargaKomp.setEditable(false);
        hargaKomp.setText("Rp. 16.500.000");
        hargaKomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaKompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(hargaKomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(merahKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumKompMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hijauKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumKompHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kuningKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumKompKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumKompBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaKomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumKompBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumKompKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumKompHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumKompMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deskLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskLapActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk: laptop ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskLapActionPerformed

    private void hargaLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaLapActionPerformed

    private void deskHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskHanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk: hp ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskHanActionPerformed

    private void hargaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaHanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaHanActionPerformed

    private void deskKompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskKompActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk: komputer ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskKompActionPerformed

    private void hargaKompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaKompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaKompActionPerformed

    private void totalTekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTekActionPerformed
        // TODO add your handling code here:
        int totMerahLap = 7000000 * (int)jumLapMer.getValue();
        String totMerahLapS = 7000000 * (int)jumLapMer.getValue()+"  =  " + "Laptop Merah  x   " + jumLapMer.getValue()+"\n";
        int totHijauLap = 8000000 * (int)jumLapHij.getValue();
        String totHijauLapS = 8000000 * (int)jumLapHij.getValue()+"  =  " + "Laptop Hijau  x   " + jumLapHij.getValue()+"\n";
        int totKuningLap = 9000000 * (int)jumLapKun.getValue();
        String totKuningLapS = 9000000 * (int)jumLapKun.getValue()+"  =  " + "Laptop Kuning  x   " + jumLapKun.getValue()+"\n";
        int totBiruLap = 10000000 * (int)jumLapBir.getValue();
        String totBiruLapS = 10000000 * (int)jumLapBir.getValue()+"  =  " + "Laptop Biru  x   " + jumLapBir.getValue()+"\n";
        
        int totMerahKomp = 16500000 * (int)jumKompMer.getValue();
        String totMerahKompS = 16500000 * (int)jumKompMer.getValue()+"  =  " + "Komputer Merah  x   " + jumKompMer.getValue()+"\n";
        int totHijauKomp = 17000000 * (int)jumKompHij.getValue();
        String totHijauKompS = 17000000 * (int)jumKompHij.getValue()+"  =  " + "Komputer Hijau  x   " + jumKompHij.getValue()+"\n";
        int totKuningKomp = 17500000 * (int)jumKompKun.getValue();
        String totKuningKompS = 17500000 * (int)jumKompKun.getValue()+"  =  " + "Komputer Kuning  x   " + jumKompKun.getValue()+"\n";
        int totBiruKomp = 18000000 * (int)jumKompBir.getValue();
        String totBiruKompS = 18000000 * (int)jumKompBir.getValue()+"  =  " + "Komputer Biru  x   " + jumKompBir.getValue()+"\n";

        
        int totMerahHan = 1005000 * (int)jumHanMer.getValue();
        String totMerahHanS = 1005000 * (int)jumHanMer.getValue()+"  =  " + "Handphone Merah  x   " + jumHanMer.getValue()+"\n";
        int totHijauHan = 2005000 * (int)jumHanHij.getValue();
        String totHijauHanS = 2005000 * (int)jumHanHij.getValue()+"  =  " + "Handphone Hijau  x   " + jumHanHij.getValue()+"\n";
        int totKuningHan = 3005000 * (int)jumHanKun.getValue();
        String totKuningHanS = 3005000 * (int)jumHanKun.getValue()+"  =  " + "Handphone Kuning  x   " + jumHanKun.getValue()+"\n";
        int totBiruHan = 4005000 * (int)jumHanBir.getValue();
        String totBiruHanS = 4005000 * (int)jumHanBir.getValue()+"  =  " + "Handphone Biru  x   " + jumHanBir.getValue()+"\n";

        String array[] = {totMerahLapS , totHijauLapS, totKuningLapS, totBiruLapS, totMerahKompS, totHijauKompS, totKuningKompS, totBiruKompS, totMerahHanS, totHijauHanS, totKuningHanS, totBiruHanS};

        for(int i =0; i< array.length; i++){
            if(array[i].charAt(0) != '0'){
                SharedInvoice.sb.append(array[i]);
            }
        }
        
        int total = totMerahLap + totHijauLap + totKuningLap + totBiruLap + totMerahKomp + totHijauKomp + totKuningKomp + totBiruKomp + totMerahHan + totHijauHan + totKuningHan + totBiruHan;
        a.setInvoice(total);
        totalBayar.setText(Integer.toString(a.getInvoice()));

        tfTotalTek.setText(Integer.toString(total));
    }//GEN-LAST:event_totalTekActionPerformed

    private void merahLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahLapActionPerformed
        // TODO add your handling code here:
        if(merahLap.isSelected()){
            hargaLap.setText("Rp. 7.000.000");
            hijauLap.setEnabled(false);
            kuningLap.setEnabled(false);
            biruLap.setEnabled(false);
        }else{
            hijauLap.setEnabled(true);
            kuningLap.setEnabled(true);
            biruLap.setEnabled(true);
        }
    }//GEN-LAST:event_merahLapActionPerformed

    private void hijauLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauLapActionPerformed
        // TODO add your handling code here:
        if(hijauLap.isSelected()){
            hargaLap.setText("Rp. 8.000.000");
            merahLap.setEnabled(false);
            kuningLap.setEnabled(false);
            biruLap.setEnabled(false);
        }else{
            merahLap.setEnabled(true);
            kuningLap.setEnabled(true);
            biruLap.setEnabled(true);
        }
    }//GEN-LAST:event_hijauLapActionPerformed

    private void kuningLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningLapActionPerformed
        // TODO add your handling code here:
        if(kuningLap.isSelected()){
            hargaLap.setText("Rp. 9.000.000");
            merahLap.setEnabled(false);
            hijauLap.setEnabled(false);
            biruLap.setEnabled(false);
        }else{
            merahLap.setEnabled(true);
            hijauLap.setEnabled(true);
            biruLap.setEnabled(true);
        }
    }//GEN-LAST:event_kuningLapActionPerformed

    private void biruLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruLapActionPerformed
        // TODO add your handling code here:
        if(biruLap.isSelected()){
            hargaLap.setText("Rp. 10.000.000");
            merahLap.setEnabled(false);
            hijauLap.setEnabled(false);
            kuningLap.setEnabled(false);
        }else{
            merahLap.setEnabled(true);
            hijauLap.setEnabled(true);
            kuningLap.setEnabled(true);
        }
    }//GEN-LAST:event_biruLapActionPerformed

    private void merahKompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahKompActionPerformed
        // TODO add your handling code here:
        if(merahKomp.isSelected()){
            hargaKomp.setText("Rp. 16.500.000");
            hijauKomp.setEnabled(false);
            kuningKomp.setEnabled(false);
            biruKomp.setEnabled(false);
        }else{
            hijauKomp.setEnabled(true);
            kuningKomp.setEnabled(true);
            biruKomp.setEnabled(true);
        }
    }//GEN-LAST:event_merahKompActionPerformed

    private void hijauKompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauKompActionPerformed
        // TODO add your handling code here:
        if(hijauKomp.isSelected()){
            hargaKomp.setText("Rp. 17.000.000");
            merahKomp.setEnabled(false);
            kuningKomp.setEnabled(false);
            biruKomp.setEnabled(false);
        }else{
            merahKomp.setEnabled(true);
            kuningKomp.setEnabled(true);
            biruKomp.setEnabled(true);
        }
    }//GEN-LAST:event_hijauKompActionPerformed

    private void kuningKompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningKompActionPerformed
        // TODO add your handling code here:
        if(kuningKomp.isSelected()){
            hargaKomp.setText("Rp. 17.500.000");
            merahKomp.setEnabled(false);
            hijauKomp.setEnabled(false);
            biruKomp.setEnabled(false);
        }else{
            merahKomp.setEnabled(true);
            hijauKomp.setEnabled(true);
            biruKomp.setEnabled(true);
        }
    }//GEN-LAST:event_kuningKompActionPerformed

    private void biruKompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruKompActionPerformed
        // TODO add your handling code here:
        if(biruKomp.isSelected()){
            hargaKomp.setText("Rp. 18.000.000");
            merahKomp.setEnabled(false);
            hijauKomp.setEnabled(false);
            kuningKomp.setEnabled(false);
        }else{
            merahKomp.setEnabled(true);
            hijauKomp.setEnabled(true);
            kuningKomp.setEnabled(true);
        }
    }//GEN-LAST:event_biruKompActionPerformed

    private void merahHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahHanActionPerformed
        // TODO add your handling code here:
        if(merahHan.isSelected()){
            hargaHan.setText("Rp. 1.005.000");
            hijauHan.setEnabled(false);
            kuningHan.setEnabled(false);
            biruHan.setEnabled(false);
        }else{
            hijauHan.setEnabled(true);
            kuningHan.setEnabled(true);
            biruHan.setEnabled(true);
        }
    }//GEN-LAST:event_merahHanActionPerformed

    private void hijauHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauHanActionPerformed
        // TODO add your handling code here:
        if(hijauHan.isSelected()){
            hargaHan.setText("Rp. 2.005.000");
            merahHan.setEnabled(false);
            kuningHan.setEnabled(false);
            biruHan.setEnabled(false);
        }else{
            merahHan.setEnabled(true);
            kuningHan.setEnabled(true);
            biruHan.setEnabled(true);
        }
    }//GEN-LAST:event_hijauHanActionPerformed

    private void kuningHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningHanActionPerformed
        // TODO add your handling code here:
        if(kuningHan.isSelected()){
            hargaHan.setText("Rp. 3.005.000");
            merahHan.setEnabled(false);
            hijauHan.setEnabled(false);
            biruHan.setEnabled(false);
        }else{
            merahHan.setEnabled(true);
            hijauHan.setEnabled(true);
            biruHan.setEnabled(true);
        }
    }//GEN-LAST:event_kuningHanActionPerformed

    private void biruHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruHanActionPerformed
        // TODO add your handling code here:
        if(biruHan.isSelected()){
            hargaHan.setText("Rp. 4.005.000");
            merahHan.setEnabled(false);
            hijauHan.setEnabled(false);
            kuningHan.setEnabled(false);
        }else{
            merahHan.setEnabled(true);
            hijauHan.setEnabled(true);
            kuningHan.setEnabled(true);
        }
    }//GEN-LAST:event_biruHanActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
         b.ta("raffi mahya", "0896666823165", "jl. kutisari utara");
        b.setVisible(true);

    }//GEN-LAST:event_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lamanTigaTek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lamanTigaTek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lamanTigaTek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lamanTigaTek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lamanTigaTek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayar;
    private javax.swing.JRadioButton biruHan;
    private javax.swing.JRadioButton biruKomp;
    private javax.swing.JRadioButton biruLap;
    private javax.swing.JButton deskHan;
    private javax.swing.JButton deskKomp;
    private javax.swing.JButton deskLap;
    private javax.swing.JTextField hargaHan;
    private javax.swing.JTextField hargaKomp;
    private javax.swing.JTextField hargaLap;
    private javax.swing.JRadioButton hijauHan;
    private javax.swing.JRadioButton hijauKomp;
    private javax.swing.JRadioButton hijauLap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jumHanBir;
    private javax.swing.JSpinner jumHanHij;
    private javax.swing.JSpinner jumHanKun;
    private javax.swing.JSpinner jumHanMer;
    private javax.swing.JSpinner jumKompBir;
    private javax.swing.JSpinner jumKompHij;
    private javax.swing.JSpinner jumKompKun;
    private javax.swing.JSpinner jumKompMer;
    private javax.swing.JSpinner jumLapBir;
    private javax.swing.JSpinner jumLapHij;
    private javax.swing.JSpinner jumLapKun;
    private javax.swing.JSpinner jumLapMer;
    private javax.swing.JRadioButton kuningHan;
    private javax.swing.JRadioButton kuningKomp;
    private javax.swing.JRadioButton kuningLap;
    private javax.swing.JRadioButton merahHan;
    private javax.swing.JRadioButton merahKomp;
    private javax.swing.JRadioButton merahLap;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField tfTotalTek;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JButton totalTek;
    // End of variables declaration//GEN-END:variables
    void nama(String nama1){
        nama.setText(nama1);
    }
    void totalHar(int harga1){
        totalBayar.setText(Integer.toString(harga1));
    }
}
