/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

/**
 *
 * @author BalbalPC
 */
public class lamanTigaPera extends javax.swing.JFrame {

    /**
     * Creates new form lamanTiga
     */
    public lamanTigaPera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalPera = new javax.swing.JButton();
        tfTotalPera = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        desk = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deskKur = new javax.swing.JButton();
        hijauKur = new javax.swing.JRadioButton();
        merahKur = new javax.swing.JRadioButton();
        kuningKur = new javax.swing.JRadioButton();
        biruKur = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jumKurBir = new javax.swing.JSpinner();
        hargaKur = new javax.swing.JTextField();
        jumKurMer = new javax.swing.JSpinner();
        jumKurHij = new javax.swing.JSpinner();
        jumKurKun = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        deskLem = new javax.swing.JButton();
        hijauLem = new javax.swing.JRadioButton();
        merahLem = new javax.swing.JRadioButton();
        kuningLem = new javax.swing.JRadioButton();
        biruLem = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jumLemBir = new javax.swing.JSpinner();
        hargaLem = new javax.swing.JTextField();
        jumLemKun = new javax.swing.JSpinner();
        jumLemHij = new javax.swing.JSpinner();
        jumLemMer = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        deskMej = new javax.swing.JButton();
        hijauMej = new javax.swing.JRadioButton();
        merahMej = new javax.swing.JRadioButton();
        kuningMej = new javax.swing.JRadioButton();
        biruMej = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jumMejBir = new javax.swing.JSpinner();
        hargaMej = new javax.swing.JTextField();
        jumMejKun = new javax.swing.JSpinner();
        jumMejHij = new javax.swing.JSpinner();
        jumMejMer = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hai, Selamat Datang");

        totalPera.setText("total harga");
        totalPera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPeraActionPerformed(evt);
            }
        });

        tfTotalPera.setEditable(false);

        nama.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalPera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalPera, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalPera)
                        .addComponent(tfTotalPera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nama)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        desk.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Kursi");

        deskKur.setText("Lihat deskripsi");
        deskKur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskKurActionPerformed(evt);
            }
        });

        hijauKur.setText("hijau");
        hijauKur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauKurActionPerformed(evt);
            }
        });

        merahKur.setText("merah");
        merahKur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahKurActionPerformed(evt);
            }
        });

        kuningKur.setText("kuning");
        kuningKur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningKurActionPerformed(evt);
            }
        });

        biruKur.setText("biru");
        biruKur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruKurActionPerformed(evt);
            }
        });

        jLabel19.setText("varian");

        hargaKur.setEditable(false);
        hargaKur.setText("Rp. 120.000");
        hargaKur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaKurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskKur, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addGroup(deskLayout.createSequentialGroup()
                        .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deskLayout.createSequentialGroup()
                                .addComponent(merahKur, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(deskLayout.createSequentialGroup()
                                .addComponent(jumKurMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauKur, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumKurHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumKurKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kuningKur, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumKurBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruKur, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaKur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaKur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahKur, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauKur, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningKur, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruKur, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskKur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumKurBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumKurMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumKurHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumKurKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Lemari");

        deskLem.setText("Lihat deskripsi");
        deskLem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskLemActionPerformed(evt);
            }
        });

        hijauLem.setText("hijau");
        hijauLem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauLemActionPerformed(evt);
            }
        });

        merahLem.setText("merah");
        merahLem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahLemActionPerformed(evt);
            }
        });

        kuningLem.setText("kuning");
        kuningLem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningLemActionPerformed(evt);
            }
        });

        biruLem.setText("biru");
        biruLem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruLemActionPerformed(evt);
            }
        });

        jLabel30.setText("varian");

        hargaLem.setEditable(false);
        hargaLem.setText("Rp. 1.005.000");
        hargaLem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaLemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskLem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel30)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahLem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumLemMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauLem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumLemHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningLem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumLemKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumLemBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruLem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaLem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaLem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahLem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauLem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningLem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruLem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskLem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumLemBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumLemKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumLemHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumLemMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Meja");

        deskMej.setText("Lihat deskripsi");
        deskMej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskMejActionPerformed(evt);
            }
        });

        hijauMej.setText("hijau");
        hijauMej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauMejActionPerformed(evt);
            }
        });

        merahMej.setText("merah");
        merahMej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahMejActionPerformed(evt);
            }
        });

        kuningMej.setText("kuning");
        kuningMej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningMejActionPerformed(evt);
            }
        });

        biruMej.setText("biru");
        biruMej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruMejActionPerformed(evt);
            }
        });

        jLabel31.setText("varian");

        hargaMej.setEditable(false);
        hargaMej.setText("Rp. 300.000");
        hargaMej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaMejActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskMej, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel31)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahMej, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMejMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauMej, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMejHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningMej, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumMejKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumMejBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruMej, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaMej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaMej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahMej, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauMej, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningMej, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruMej, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskMej, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMejBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMejKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMejHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumMejMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deskKurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskKurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskKurActionPerformed

    private void hargaKurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaKurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaKurActionPerformed

    private void deskLemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskLemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskLemActionPerformed

    private void hargaLemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaLemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaLemActionPerformed

    private void deskMejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskMejActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskMejActionPerformed

    private void hargaMejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaMejActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaMejActionPerformed

    private void merahKurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahKurActionPerformed
        // TODO add your handling code here:
        if(merahKur.isSelected()){
            hargaKur.setText("Rp. 120.000");
            hijauKur.setEnabled(false);
            kuningKur.setEnabled(false);
            biruKur.setEnabled(false);
        }else{
            hijauKur.setEnabled(true);
            kuningKur.setEnabled(true);
            biruKur.setEnabled(true);
        }
    }//GEN-LAST:event_merahKurActionPerformed

    private void totalPeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPeraActionPerformed
        // TODO add your handling code here:
        int totMerahKur = 120000 * (int)jumKurMer.getValue();
        int totHijauKur = 130000 * (int)jumKurHij.getValue();
        int totKuningKur = 140000 * (int)jumKurKun.getValue();
        int totBiruKur = 150000 * (int)jumKurBir.getValue();
        
        int totMerahMej = 300000 * (int)jumMejMer.getValue();
        int totHijauMej = 350000 * (int)jumMejHij.getValue();
        int totKuningMej = 400000 * (int)jumMejKun.getValue();
        int totBiruMej = 450000 * (int)jumMejBir.getValue();
        
        int totMerahLem = 1005000 * (int)jumLemMer.getValue();
        int totHijauLem = 1100000 * (int)jumLemHij.getValue();
        int totKuningLem = 1150000 * (int)jumLemKun.getValue();
        int totBiruLem = 1200000 * (int)jumLemBir.getValue();
        
        int total = totMerahKur + totHijauKur + totKuningKur + totBiruKur + totMerahMej + totHijauMej + totKuningMej + totBiruMej + totMerahLem + totHijauLem + totKuningLem + totBiruLem;
        
        tfTotalPera.setText(Integer.toString(total));
    }//GEN-LAST:event_totalPeraActionPerformed

    private void hijauKurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauKurActionPerformed
        // TODO add your handling code here:
         if(hijauKur.isSelected()){
            hargaKur.setText("Rp. 130.000");
            merahKur.setEnabled(false);
            kuningKur.setEnabled(false);
            biruKur.setEnabled(false);
        }else{
            merahKur.setEnabled(true);
            kuningKur.setEnabled(true);
            biruKur.setEnabled(true);
        }
    }//GEN-LAST:event_hijauKurActionPerformed

    private void kuningKurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningKurActionPerformed
        // TODO add your handling code here:
        if(kuningKur.isSelected()){
            hargaKur.setText("Rp. 140.000");
            merahKur.setEnabled(false);
            hijauKur.setEnabled(false);
            biruKur.setEnabled(false);
        }else{
            merahKur.setEnabled(true);
            hijauKur.setEnabled(true);
            biruKur.setEnabled(true);
        }
    }//GEN-LAST:event_kuningKurActionPerformed

    private void biruKurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruKurActionPerformed
        // TODO add your handling code here:
        if(biruKur.isSelected()){
            hargaKur.setText("Rp. 150.000");
            merahKur.setEnabled(false);
            hijauKur.setEnabled(false);
            kuningKur.setEnabled(false);
        }else{
            merahKur.setEnabled(true);
            hijauKur.setEnabled(true);
            kuningKur.setEnabled(true);
        }
    }//GEN-LAST:event_biruKurActionPerformed

    private void merahMejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahMejActionPerformed
        // TODO add your handling code here:
        if(merahMej.isSelected()){
            hargaMej.setText("Rp. 300.000");
            hijauMej.setEnabled(false);
            kuningMej.setEnabled(false);
            biruMej.setEnabled(false);
        }else{
            hijauMej.setEnabled(true);
            kuningMej.setEnabled(true);
            biruMej.setEnabled(true);
        }

    }//GEN-LAST:event_merahMejActionPerformed

    private void hijauMejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauMejActionPerformed
        // TODO add your handling code here:
         if(hijauMej.isSelected()){
            hargaMej.setText("Rp. 350.000");
            merahMej.setEnabled(false);
            kuningMej.setEnabled(false);
            biruMej.setEnabled(false);
        }else{
            merahMej.setEnabled(true);
            kuningMej.setEnabled(true);
            biruMej.setEnabled(true);
        }
    }//GEN-LAST:event_hijauMejActionPerformed

    private void kuningMejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningMejActionPerformed
        // TODO add your handling code here:
         if(kuningMej.isSelected()){
            hargaMej.setText("Rp. 400.000");
            merahMej.setEnabled(false);
            hijauMej.setEnabled(false);
            biruMej.setEnabled(false);
        }else{
            merahMej.setEnabled(true);
            hijauMej.setEnabled(true);
            biruMej.setEnabled(true);
        }
    }//GEN-LAST:event_kuningMejActionPerformed

    private void biruMejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruMejActionPerformed
        // TODO add your handling code here:
        if(biruMej.isSelected()){
            hargaMej.setText("Rp. 450.000");
            merahMej.setEnabled(false);
            hijauMej.setEnabled(false);
            kuningMej.setEnabled(false);
        }else{
            merahMej.setEnabled(true);
            hijauMej.setEnabled(true);
            kuningMej.setEnabled(true);
        }
    }//GEN-LAST:event_biruMejActionPerformed

    private void merahLemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahLemActionPerformed
        // TODO add your handling code here:
        if(merahLem.isSelected()){
            hargaLem.setText("Rp. 1.005.000");
            hijauLem.setEnabled(false);
            kuningLem.setEnabled(false);
            biruLem.setEnabled(false);
        }else{
            hijauLem.setEnabled(true);
            kuningLem.setEnabled(true);
            biruLem.setEnabled(true);
        }

    }//GEN-LAST:event_merahLemActionPerformed

    private void hijauLemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauLemActionPerformed
        // TODO add your handling code here:
         if(hijauLem.isSelected()){
            hargaLem.setText("Rp. 1.100.000");
            merahLem.setEnabled(false);
            kuningLem.setEnabled(false);
            biruLem.setEnabled(false);
        }else{
            merahLem.setEnabled(true);
            kuningLem.setEnabled(true);
            biruLem.setEnabled(true);
        }
    }//GEN-LAST:event_hijauLemActionPerformed

    private void kuningLemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningLemActionPerformed
        // TODO add your handling code here:
         if(kuningLem.isSelected()){
            hargaLem.setText("Rp. 1.150.000");
            merahLem.setEnabled(false);
            hijauLem.setEnabled(false);
            biruLem.setEnabled(false);
        }else{
            merahLem.setEnabled(true);
            hijauLem.setEnabled(true);
            biruLem.setEnabled(true);
        }
    }//GEN-LAST:event_kuningLemActionPerformed

    private void biruLemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruLemActionPerformed
        // TODO add your handling code here:
        if(biruLem.isSelected()){
            hargaLem.setText("Rp. 1.200.000");
            merahLem.setEnabled(false);
            hijauLem.setEnabled(false);
            kuningLem.setEnabled(false);
        }else{
            merahLem.setEnabled(true);
            hijauLem.setEnabled(true);
            kuningLem.setEnabled(true);
        }
    }//GEN-LAST:event_biruLemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lamanTigaPera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lamanTigaPera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lamanTigaPera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lamanTigaPera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lamanTigaPera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton biruKur;
    private javax.swing.JRadioButton biruLem;
    private javax.swing.JRadioButton biruMej;
    private javax.swing.JPanel desk;
    private javax.swing.JButton deskKur;
    private javax.swing.JButton deskLem;
    private javax.swing.JButton deskMej;
    private javax.swing.JTextField hargaKur;
    private javax.swing.JTextField hargaLem;
    private javax.swing.JTextField hargaMej;
    private javax.swing.JRadioButton hijauKur;
    private javax.swing.JRadioButton hijauLem;
    private javax.swing.JRadioButton hijauMej;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jumKurBir;
    private javax.swing.JSpinner jumKurHij;
    private javax.swing.JSpinner jumKurKun;
    private javax.swing.JSpinner jumKurMer;
    private javax.swing.JSpinner jumLemBir;
    private javax.swing.JSpinner jumLemHij;
    private javax.swing.JSpinner jumLemKun;
    private javax.swing.JSpinner jumLemMer;
    private javax.swing.JSpinner jumMejBir;
    private javax.swing.JSpinner jumMejHij;
    private javax.swing.JSpinner jumMejKun;
    private javax.swing.JSpinner jumMejMer;
    private javax.swing.JRadioButton kuningKur;
    private javax.swing.JRadioButton kuningLem;
    private javax.swing.JRadioButton kuningMej;
    private javax.swing.JRadioButton merahKur;
    private javax.swing.JRadioButton merahLem;
    private javax.swing.JRadioButton merahMej;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField tfTotalPera;
    private javax.swing.JButton totalPera;
    // End of variables declaration//GEN-END:variables
      void nama(String nama1){
        nama.setText(nama1);
    }

}
