/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import javax.swing.JOptionPane;
/**
 *
 * @author BalbalPC
 */
public class lamanTigaSpo extends javax.swing.JFrame {
    total a = new total();
    private lamanInvoice b;
    /**
     * Creates new form lamanTiga
     */
    public lamanTigaSpo() {
        initComponents();
                b = new lamanInvoice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalSpo = new javax.swing.JButton();
        tfTotalSpo = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();
        totalBayar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deskBar = new javax.swing.JButton();
        hijauBar = new javax.swing.JRadioButton();
        merahBar = new javax.swing.JRadioButton();
        kuningBar = new javax.swing.JRadioButton();
        biruBar = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jumBarBir = new javax.swing.JSpinner();
        hargaBar = new javax.swing.JTextField();
        jumBarKun = new javax.swing.JSpinner();
        jumBarHij = new javax.swing.JSpinner();
        jumBarMer = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        deskSep = new javax.swing.JButton();
        hijauSep = new javax.swing.JRadioButton();
        merahSep = new javax.swing.JRadioButton();
        kuningSep = new javax.swing.JRadioButton();
        biruSep = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jumSepBir = new javax.swing.JSpinner();
        hargaSep = new javax.swing.JTextField();
        jumSepKun = new javax.swing.JSpinner();
        jumSepHij = new javax.swing.JSpinner();
        jumSepMer = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        deskBol = new javax.swing.JButton();
        hijauBol = new javax.swing.JRadioButton();
        merahBol = new javax.swing.JRadioButton();
        kuningBol = new javax.swing.JRadioButton();
        biruBol = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jumBolBir = new javax.swing.JSpinner();
        hargaBol = new javax.swing.JTextField();
        jumBolKun = new javax.swing.JSpinner();
        jumBolHij = new javax.swing.JSpinner();
        jumBolMer = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hai, Selamat Datang");

        totalSpo.setText("total harga");
        totalSpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSpoActionPerformed(evt);
            }
        });

        tfTotalSpo.setEditable(false);

        nama.setText("jLabel2");

        bayar.setText("bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        totalBayar.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalSpo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTotalSpo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalSpo)
                        .addComponent(tfTotalSpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nama)
                        .addComponent(bayar)
                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Barbel");

        deskBar.setText("Lihat deskripsi");
        deskBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskBarActionPerformed(evt);
            }
        });

        hijauBar.setText("hijau");
        hijauBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauBarActionPerformed(evt);
            }
        });

        merahBar.setText("merah");
        merahBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahBarActionPerformed(evt);
            }
        });

        kuningBar.setText("kuning");
        kuningBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningBarActionPerformed(evt);
            }
        });

        biruBar.setText("biru");
        biruBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruBarActionPerformed(evt);
            }
        });

        jLabel19.setText("varian");

        hargaBar.setEditable(false);
        hargaBar.setText("Rp. 200.000");
        hargaBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaBarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskBar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahBar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBarMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauBar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBarHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningBar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBarKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumBarBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruBar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskBar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBarBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBarKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBarHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBarMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Sepatu Lari");

        deskSep.setText("Lihat deskripsi");
        deskSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskSepActionPerformed(evt);
            }
        });

        hijauSep.setText("hijau");
        hijauSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauSepActionPerformed(evt);
            }
        });

        merahSep.setText("merah");
        merahSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahSepActionPerformed(evt);
            }
        });

        kuningSep.setText("kuning");
        kuningSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningSepActionPerformed(evt);
            }
        });

        biruSep.setText("biru");
        biruSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruSepActionPerformed(evt);
            }
        });

        jLabel30.setText("varian");

        hargaSep.setEditable(false);
        hargaSep.setText("Rp. 435.000");
        hargaSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaSepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskSep, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel30)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahSep, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumSepMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauSep, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumSepHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningSep, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumSepKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumSepBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruSep, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahSep, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauSep, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningSep, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruSep, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskSep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumSepBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumSepKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumSepHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumSepMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Bola Basket");

        deskBol.setText("Lihat deskripsi");
        deskBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskBolActionPerformed(evt);
            }
        });

        hijauBol.setText("hijau");
        hijauBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauBolActionPerformed(evt);
            }
        });

        merahBol.setText("merah");
        merahBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahBolActionPerformed(evt);
            }
        });

        kuningBol.setText("kuning");
        kuningBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningBolActionPerformed(evt);
            }
        });

        biruBol.setText("biru");
        biruBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruBolActionPerformed(evt);
            }
        });

        jLabel31.setText("varian");

        hargaBol.setEditable(false);
        hargaBol.setText("Rp. 250.000");
        hargaBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaBolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskBol, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel31)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahBol, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBolMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauBol, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBolHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningBol, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumBolKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumBolBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruBol, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaBol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaBol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahBol, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauBol, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningBol, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruBol, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskBol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBolBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBolKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBolHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumBolMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deskBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskBarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk: barbel ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskBarActionPerformed

    private void hargaBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBarActionPerformed

    private void deskSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskSepActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk: sepatu ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskSepActionPerformed

    private void hargaSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaSepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaSepActionPerformed

    private void deskBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskBolActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk: bola basket ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskBolActionPerformed

    private void hargaBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaBolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBolActionPerformed

    private void merahBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahBarActionPerformed
        // TODO add your handling code here:
        if(merahBar.isSelected()){
            hargaBar.setText("Rp. 200.000");
            hijauBar.setEnabled(false);
            kuningBar.setEnabled(false);
            biruBar.setEnabled(false);
        }else{
            hijauBar.setEnabled(true);
            kuningBar.setEnabled(true);
            biruBar.setEnabled(true);
        }
    }//GEN-LAST:event_merahBarActionPerformed

    private void totalSpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSpoActionPerformed
        // TODO add your handling code here:
        int totMerahBar = 200000 * (int)jumBarMer.getValue();
        String totMerahBarS = 200000 * (int)jumBarMer.getValue()+"  =  " + "Barbel Merah  x   " + jumBarMer.getValue()+"\n";
        int totHijauBar = 230000 * (int)jumBarHij.getValue();
        String totHijauBarS = 230000 * (int)jumBarHij.getValue()+"  =  " + "Barbel Hijau  x   " + jumBarHij.getValue()+"\n";
        int totKuningBar = 260000 * (int)jumBarKun.getValue();
        String totKuningBarS = 260000 * (int)jumBarKun.getValue()+"  =  " + "Barbel Kuning  x   " + jumBarKun.getValue()+"\n";
        int totBiruBar = 290000 * (int)jumBarBir.getValue();
        String totBiruBarS = 290000 * (int)jumBarBir.getValue()+"  =  " + "Barbel Biru  x   " + jumBarBir.getValue()+"\n";
        
        int totMerahBol = 250000 * (int)jumBolMer.getValue();
        String totMerahBolS = 250000 * (int)jumBolMer.getValue()+"  =  " + "Bola Basket Merah  x   " + jumBolMer.getValue()+"\n";
        int totHijauBol = 300000 * (int)jumBolHij.getValue();
        String totHijauBolS = 300000 * (int)jumBolHij.getValue()+"  =  " + "Bola Basket Hijau  x   " + jumBolHij.getValue()+"\n";
        int totKuningBol = 350000 * (int)jumBolKun.getValue();
        String totKuningBolS = 350000 * (int)jumBolKun.getValue()+"  =  " + "Bola Basket Kuning  x   " + jumBolKun.getValue()+"\n";
        int totBiruBol = 400000 * (int)jumBolBir.getValue();
        String totBiruBolS = 400000 * (int)jumBolBir.getValue()+"  =  " + "Bola Basket Biru  x   " + jumBolBir.getValue()+"\n";
        
        int totMerahSep = 435000 * (int)jumSepMer.getValue();
        String totMerahSepS = 435000 * (int)jumSepMer.getValue()+"  =  " + "Lipstrik Merah  x   " + jumSepMer.getValue()+"\n";
        int totHijauSep = 470000 * (int)jumSepHij.getValue();
        String totHijauSepS = 470000 * (int)jumSepHij.getValue()+"  =  " + "Lipstrik Hijau  x   " + jumSepHij.getValue()+"\n";
        int totKuningSep = 505000 * (int)jumSepKun.getValue();
        String totKuningSepS = 505000 * (int)jumSepKun.getValue()+"  =  " + "Lipstrik Kuning  x   " + jumSepKun.getValue()+"\n";
        int totBiruSep = 540000 * (int)jumSepBir.getValue();
        String totBiruSepS = 540000 * (int)jumSepBir.getValue()+"  =  " + "Lipstrik Biru  x   " + jumSepBir.getValue()+"\n";
        
        String array[] = {totMerahBarS , totHijauBarS, totKuningBarS, totBiruBarS, totMerahBolS, totHijauBolS, totKuningBolS, totBiruBolS, totMerahSepS, totHijauSepS, totKuningSepS, totBiruSepS};

        for(int i =0; i< array.length; i++){
            if(array[i].charAt(0) != '0'){
                SharedInvoice.sb.append(array[i]);
            }
        }
        
        int total = totMerahBar + totHijauBar + totKuningBar + totBiruBar + totMerahBol + totHijauBol + totKuningBol + totBiruBol + totMerahSep + totHijauSep + totKuningSep + totBiruSep;
        a.setInvoice(total);
        totalBayar.setText(Integer.toString(a.getInvoice()));

        tfTotalSpo.setText(Integer.toString(total));
    }//GEN-LAST:event_totalSpoActionPerformed

    private void hijauBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauBarActionPerformed
        // TODO add your handling code here:
        if(hijauBar.isSelected()){
            hargaBar.setText("Rp. 230.000");
            merahBar.setEnabled(false);
            kuningBar.setEnabled(false);
            biruBar.setEnabled(false);
        }else{
            merahBar.setEnabled(true);
            kuningBar.setEnabled(true);
            biruBar.setEnabled(true);
        }
    }//GEN-LAST:event_hijauBarActionPerformed

    private void kuningBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningBarActionPerformed
        // TODO add your handling code here:
        if(kuningBar.isSelected()){
            hargaBar.setText("Rp. 260.000");
            merahBar.setEnabled(false);
            hijauBar.setEnabled(false);
            biruBar.setEnabled(false);
        }else{
            merahBar.setEnabled(true);
            hijauBar.setEnabled(true);
            biruBar.setEnabled(true);
        }
    }//GEN-LAST:event_kuningBarActionPerformed

    private void biruBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruBarActionPerformed
        // TODO add your handling code here:
        if(biruBar.isSelected()){
            hargaBar.setText("Rp. 290.000");
            merahBar.setEnabled(false);
            hijauBar.setEnabled(false);
            kuningBar.setEnabled(false);
        }else{
            merahBar.setEnabled(true);
            hijauBar.setEnabled(true);
            kuningBar.setEnabled(true);
        }
    }//GEN-LAST:event_biruBarActionPerformed

    private void merahBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahBolActionPerformed
        // TODO add your handling code here:
        if(merahBol.isSelected()){
            hargaBol.setText("Rp. 250.000");
            hijauBol.setEnabled(false);
            kuningBol.setEnabled(false);
            biruBol.setEnabled(false);
        }else{
            hijauBol.setEnabled(true);
            kuningBol.setEnabled(true);
            biruBol.setEnabled(true);
        }
    }//GEN-LAST:event_merahBolActionPerformed

    private void hijauBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauBolActionPerformed
        // TODO add your handling code here:
        if(hijauBol.isSelected()){
            hargaBol.setText("Rp. 300.000");
            merahBol.setEnabled(false);
            kuningBol.setEnabled(false);
            biruBol.setEnabled(false);
        }else{
            merahBol.setEnabled(true);
            kuningBol.setEnabled(true);
            biruBol.setEnabled(true);
        }
    }//GEN-LAST:event_hijauBolActionPerformed

    private void kuningBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningBolActionPerformed
        // TODO add your handling code here:
        if(kuningBol.isSelected()){
            hargaBol.setText("Rp. 350.000");
            merahBol.setEnabled(false);
            hijauBol.setEnabled(false);
            biruBol.setEnabled(false);
        }else{
            merahBol.setEnabled(true);
            hijauBol.setEnabled(true);
            biruBol.setEnabled(true);
        }
    }//GEN-LAST:event_kuningBolActionPerformed

    private void biruBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruBolActionPerformed
        // TODO add your handling code here:
        if(biruBol.isSelected()){
            hargaBol.setText("Rp. 400.000");
            merahBol.setEnabled(false);
            hijauBol.setEnabled(false);
            kuningBol.setEnabled(false);
        }else{
            merahBol.setEnabled(true);
            hijauBol.setEnabled(true);
            kuningBol.setEnabled(true);
        }
    }//GEN-LAST:event_biruBolActionPerformed

    private void merahSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahSepActionPerformed
        // TODO add your handling code here:
        if(merahSep.isSelected()){
            hargaSep.setText("Rp. 435.000");
            hijauSep.setEnabled(false);
            kuningSep.setEnabled(false);
            biruSep.setEnabled(false);
        }else{
            hijauSep.setEnabled(true);
            kuningSep.setEnabled(true);
            biruSep.setEnabled(true);
        }
    }//GEN-LAST:event_merahSepActionPerformed

    private void hijauSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauSepActionPerformed
        // TODO add your handling code here:
        if(hijauSep.isSelected()){
            hargaSep.setText("Rp. 470.000");
            merahSep.setEnabled(false);
            kuningSep.setEnabled(false);
            biruSep.setEnabled(false);
        }else{
            merahSep.setEnabled(true);
            kuningSep.setEnabled(true);
            biruSep.setEnabled(true);
        }
    }//GEN-LAST:event_hijauSepActionPerformed

    private void kuningSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningSepActionPerformed
        // TODO add your handling code here:
        if(kuningSep.isSelected()){
            hargaSep.setText("Rp. 505.000");
            merahSep.setEnabled(false);
            hijauSep.setEnabled(false);
            biruSep.setEnabled(false);
        }else{
            merahSep.setEnabled(true);
            hijauSep.setEnabled(true);
            biruSep.setEnabled(true);
        }
    }//GEN-LAST:event_kuningSepActionPerformed

    private void biruSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruSepActionPerformed
        // TODO add your handling code here:
        if(biruSep.isSelected()){
            hargaSep.setText("Rp. 540.000");
            merahSep.setEnabled(false);
            hijauSep.setEnabled(false);
            kuningSep.setEnabled(false);
        }else{
            merahSep.setEnabled(true);
            hijauSep.setEnabled(true);
            kuningSep.setEnabled(true);
        }
    }//GEN-LAST:event_biruSepActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
         b.ta("raffi mahya", "0896666823165", "jl. kutisari utara");
        b.setVisible(true);
    }//GEN-LAST:event_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lamanTigaSpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lamanTigaSpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lamanTigaSpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lamanTigaSpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lamanTigaSpo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayar;
    private javax.swing.JRadioButton biruBar;
    private javax.swing.JRadioButton biruBol;
    private javax.swing.JRadioButton biruSep;
    private javax.swing.JButton deskBar;
    private javax.swing.JButton deskBol;
    private javax.swing.JButton deskSep;
    private javax.swing.JTextField hargaBar;
    private javax.swing.JTextField hargaBol;
    private javax.swing.JTextField hargaSep;
    private javax.swing.JRadioButton hijauBar;
    private javax.swing.JRadioButton hijauBol;
    private javax.swing.JRadioButton hijauSep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jumBarBir;
    private javax.swing.JSpinner jumBarHij;
    private javax.swing.JSpinner jumBarKun;
    private javax.swing.JSpinner jumBarMer;
    private javax.swing.JSpinner jumBolBir;
    private javax.swing.JSpinner jumBolHij;
    private javax.swing.JSpinner jumBolKun;
    private javax.swing.JSpinner jumBolMer;
    private javax.swing.JSpinner jumSepBir;
    private javax.swing.JSpinner jumSepHij;
    private javax.swing.JSpinner jumSepKun;
    private javax.swing.JSpinner jumSepMer;
    private javax.swing.JRadioButton kuningBar;
    private javax.swing.JRadioButton kuningBol;
    private javax.swing.JRadioButton kuningSep;
    private javax.swing.JRadioButton merahBar;
    private javax.swing.JRadioButton merahBol;
    private javax.swing.JRadioButton merahSep;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField tfTotalSpo;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JButton totalSpo;
    // End of variables declaration//GEN-END:variables
    void nama(String nama1){
        nama.setText(nama1);
    }
    void totalHar(int harga1){
        totalBayar.setText(Integer.toString(harga1));
    }
}
