/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JOptionPane;
/**
 *
 * @author BalbalPC
 */
public class lamanTigaPer extends javax.swing.JFrame {
    total a = new total();
        private lamanInvoice b;
    /**
     * Creates new form lamanTiga
     */
    public lamanTigaPer() {
        initComponents();
                b = new lamanInvoice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalPer = new javax.swing.JButton();
        tfTotalPer = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        totalBayar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deskDril = new javax.swing.JButton();
        hijauDril = new javax.swing.JRadioButton();
        merahDril = new javax.swing.JRadioButton();
        kuningDril = new javax.swing.JRadioButton();
        biruDril = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jumDrillBir = new javax.swing.JSpinner();
        hargaDril = new javax.swing.JTextField();
        jumDrillKun = new javax.swing.JSpinner();
        jumDrillHij = new javax.swing.JSpinner();
        jumDrillMer = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        deskObe = new javax.swing.JButton();
        hijauObe = new javax.swing.JRadioButton();
        merahObe = new javax.swing.JRadioButton();
        kuningObe = new javax.swing.JRadioButton();
        biruObe = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jumObeBir = new javax.swing.JSpinner();
        hargaObe = new javax.swing.JTextField();
        jumObeKun = new javax.swing.JSpinner();
        jumObeHij = new javax.swing.JSpinner();
        jumObeMer = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        deskTool = new javax.swing.JButton();
        hijauTool = new javax.swing.JRadioButton();
        merahTool = new javax.swing.JRadioButton();
        kuningTool = new javax.swing.JRadioButton();
        biruTool = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jumToolBir = new javax.swing.JSpinner();
        hargaTool = new javax.swing.JTextField();
        jumToolKun = new javax.swing.JSpinner();
        jumToolHij = new javax.swing.JSpinner();
        jumToolMer = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hai, Selamat Datang");

        totalPer.setText("total harga");
        totalPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPerActionPerformed(evt);
            }
        });

        tfTotalPer.setEditable(false);

        nama.setText("jLabel2");

        jButton1.setText("bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        totalBayar.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalPer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalPer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalPer)
                        .addComponent(tfTotalPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nama)
                        .addComponent(jButton1)
                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Drill Cordless");

        deskDril.setText("Lihat deskripsi");
        deskDril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskDrilActionPerformed(evt);
            }
        });

        hijauDril.setText("hijau");
        hijauDril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauDrilActionPerformed(evt);
            }
        });

        merahDril.setText("merah");
        merahDril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahDrilActionPerformed(evt);
            }
        });

        kuningDril.setText("kuning");
        kuningDril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningDrilActionPerformed(evt);
            }
        });

        biruDril.setText("biru");
        biruDril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruDrilActionPerformed(evt);
            }
        });

        jLabel19.setText("varian");

        hargaDril.setEditable(false);
        hargaDril.setText("Rp. 740.000");
        hargaDril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaDrilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskDril, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahDril, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumDrillMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauDril, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumDrillHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningDril, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumDrillKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumDrillBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruDril, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaDril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaDril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahDril, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauDril, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningDril, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruDril, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskDril, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumDrillBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumDrillKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumDrillHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumDrillMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Obeng +/-");

        deskObe.setText("Lihat deskripsi");
        deskObe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskObeActionPerformed(evt);
            }
        });

        hijauObe.setText("hijau");
        hijauObe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauObeActionPerformed(evt);
            }
        });

        merahObe.setText("merah");
        merahObe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahObeActionPerformed(evt);
            }
        });

        kuningObe.setText("kuning");
        kuningObe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningObeActionPerformed(evt);
            }
        });

        biruObe.setText("biru");
        biruObe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruObeActionPerformed(evt);
            }
        });

        jLabel30.setText("varian");

        hargaObe.setEditable(false);
        hargaObe.setText("Rp. 35.000");
        hargaObe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaObeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskObe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel30)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahObe, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumObeMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauObe, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumObeHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningObe, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumObeKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumObeBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruObe, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaObe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaObe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahObe, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauObe, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningObe, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruObe, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskObe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumObeBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumObeKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumObeHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumObeMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Toolbox");

        deskTool.setText("Lihat deskripsi");
        deskTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskToolActionPerformed(evt);
            }
        });

        hijauTool.setText("hijau");
        hijauTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hijauToolActionPerformed(evt);
            }
        });

        merahTool.setText("merah");
        merahTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merahToolActionPerformed(evt);
            }
        });

        kuningTool.setText("kuning");
        kuningTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuningToolActionPerformed(evt);
            }
        });

        biruTool.setText("biru");
        biruTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biruToolActionPerformed(evt);
            }
        });

        jLabel31.setText("varian");

        hargaTool.setEditable(false);
        hargaTool.setText("Rp. 170.000");
        hargaTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaToolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deskTool, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel31)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merahTool, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumToolMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hijauTool, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumToolHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kuningTool, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumToolKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumToolBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biruTool, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hargaTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merahTool, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hijauTool, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuningTool, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biruTool, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deskTool, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumToolBir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumToolKun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumToolHij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumToolMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deskDrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskDrilActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk:  drill ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskDrilActionPerformed

    private void hargaDrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaDrilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaDrilActionPerformed

    private void deskObeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskObeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk:  obeng ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskObeActionPerformed

    private void hargaObeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaObeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaObeActionPerformed

    private void deskToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskToolActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "deskripsi produk:  tool box ini sangat wadidau sekali, ada 4 varian");
    }//GEN-LAST:event_deskToolActionPerformed

    private void hargaToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaToolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaToolActionPerformed

    private void merahDrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahDrilActionPerformed
        // TODO add your handling code here:
        if(merahDril.isSelected()){
            hargaDril.setText("740.000");
            hijauDril.setEnabled(false);
            kuningDril.setEnabled(false);
            biruDril.setEnabled(false);
        }else{
            hijauDril.setEnabled(true);
            kuningDril.setEnabled(true);
            biruDril.setEnabled(true);
        }
    }//GEN-LAST:event_merahDrilActionPerformed

    private void totalPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPerActionPerformed
        // TODO add your handling code here:
        int totMerahDrill = 740000 * (int)jumDrillMer.getValue();
        String totMerahDrillS = 740000 * (int)jumDrillMer.getValue()+"  =  " + "Drill Merah  x   " + jumDrillMer.getValue()+"\n";
        int totHijauDrill = 840000 * (int)jumDrillHij.getValue();
        String totHijauDrillS = 840000 * (int)jumDrillHij.getValue()+"  =  " + "Drill Hijau  x   " + jumDrillHij.getValue()+"\n";
        int totKuningDrill = 940000 * (int)jumDrillKun.getValue();
        String totKuningDrillS = 940000 * (int)jumDrillKun.getValue()+"  =  " + "Drill Kuning  x   " + jumDrillKun.getValue()+"\n";
        int totBiruDrill = 1040000 * (int)jumDrillBir.getValue();
        String totBiruDrillS = 104000 * (int)jumDrillBir.getValue()+"  =  " + "Drill Biru  x   " + jumDrillBir.getValue()+"\n";
        
        int totMerahTool = 170000 * (int)jumToolMer.getValue();
        String totMerahToolS = 170000 * (int)jumToolMer.getValue()+"  =  " + "Tool Merah  x   " + jumToolMer.getValue()+"\n";
        int totHijauTool = 180000 * (int)jumToolHij.getValue();
        String totHijauToolS = 180000 * (int)jumToolHij.getValue()+"  =  " + "Tool Hijau  x   " + jumToolHij.getValue()+"\n";
        int totKuningTool = 190000 * (int)jumToolKun.getValue();
        String totKuningToolS = 190000 * (int)jumToolKun.getValue()+"  =  " + "Tool Kuning  x   " + jumToolKun.getValue()+"\n";
        int totBiruTool = 200000 * (int)jumToolBir.getValue();
        String totBiruToolS = 200000 * (int)jumToolBir.getValue()+"  =  " + "Tool Biru  x   " + jumToolBir.getValue()+"\n";
        
        int totMerahObe = 35000 * (int)jumObeMer.getValue();
        String totMerahObeS = 35000 * (int)jumObeMer.getValue()+"  =  " + "Obeng Merah  x   " + jumObeMer.getValue()+"\n";
        int totHijauObe = 40000 * (int)jumObeHij.getValue();
        String totHijauObeS = 40000 * (int)jumObeHij.getValue()+"  =  " + "Obeng Hijau  x   " + jumObeHij.getValue()+"\n";
        int totKuningObe = 45000 * (int)jumObeKun.getValue();
        String totKuningObeS = 45000 * (int)jumObeKun.getValue()+"  =  " + "Obeng Kuning  x   " + jumObeKun.getValue()+"\n";
        int totBiruObe = 50000 * (int)jumObeBir.getValue();
        String totBiruObeS = 50000 * (int)jumObeBir.getValue()+"  =  " + "Obeng Biru  x   " + jumObeBir.getValue()+"\n";
        
        String array[] = {totMerahDrillS , totHijauDrillS, totKuningDrillS, totBiruDrillS, totMerahToolS, totHijauToolS, totKuningToolS, totBiruToolS, totMerahObeS, totHijauObeS, totKuningObeS, totBiruObeS};

        for(int i =0; i< array.length; i++){
            if(array[i].charAt(0) != '0'){
                SharedInvoice.sb.append(array[i]);
        }
    }
        
        int total = totMerahDrill + totHijauDrill + totKuningDrill + totBiruDrill + totMerahTool + totHijauTool + totKuningTool + totBiruTool + totMerahObe + totHijauObe + totKuningObe + totBiruObe;
        a.setInvoice(total);
        totalBayar.setText(Integer.toString(a.getInvoice()));
        tfTotalPer.setText(Integer.toString(total));
    }//GEN-LAST:event_totalPerActionPerformed

    private void hijauDrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauDrilActionPerformed
        // TODO add your handling code here:
         if(hijauDril.isSelected()){
            hargaDril.setText("Rp. 840.000");
            merahDril.setEnabled(false);
            kuningDril.setEnabled(false);
            biruDril.setEnabled(false);
        }else{
            merahDril.setEnabled(true);
            kuningDril.setEnabled(true);
            biruDril.setEnabled(true);
        }
    }//GEN-LAST:event_hijauDrilActionPerformed

    private void hijauToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauToolActionPerformed
        // TODO add your handling code here:
        if(hijauTool.isSelected()){
            hargaTool.setText("Rp. 180.000");
            merahTool.setEnabled(false);
            kuningTool.setEnabled(false);
            biruTool.setEnabled(false);
        }else{
            merahTool.setEnabled(true);
            kuningTool.setEnabled(true);
            biruTool.setEnabled(true);
        }
    }//GEN-LAST:event_hijauToolActionPerformed

    private void kuningDrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningDrilActionPerformed
        // TODO add your handling code here:
         if(kuningDril.isSelected()){
            hargaDril.setText("Rp. 90.000.000");
            merahDril.setEnabled(false);
            hijauDril.setEnabled(false);
            biruDril.setEnabled(false);
        }else{
            merahDril.setEnabled(true);
            hijauDril.setEnabled(true);
            biruDril.setEnabled(true);
        }
    }//GEN-LAST:event_kuningDrilActionPerformed

    private void biruDrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruDrilActionPerformed
        // TODO add your handling code here:
        if(biruDril.isSelected()){
            hargaDril.setText("Rp. 104.000");
            merahDril.setEnabled(false);
            hijauDril.setEnabled(false);
            kuningDril.setEnabled(false);
        }else{
            merahDril.setEnabled(true);
            hijauDril.setEnabled(true);
            kuningDril.setEnabled(true);
        }

    }//GEN-LAST:event_biruDrilActionPerformed

    private void merahToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahToolActionPerformed
        // TODO add your handling code here:
        if(merahTool.isSelected()){
            hargaTool.setText("Rp. 170.000");
            hijauTool.setEnabled(false);
            kuningTool.setEnabled(false);
            biruTool.setEnabled(false);
        }else{
            hijauTool.setEnabled(true);
            kuningTool.setEnabled(true);
            biruTool.setEnabled(true);
        }
    }//GEN-LAST:event_merahToolActionPerformed

    private void kuningToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningToolActionPerformed
        // TODO add your handling code here:
         if(kuningTool.isSelected()){
            hargaTool.setText("Rp. 190.000");
            merahTool.setEnabled(false);
            hijauTool.setEnabled(false);
            biruTool.setEnabled(false);
        }else{
            merahTool.setEnabled(true);
            hijauTool.setEnabled(true);
            biruTool.setEnabled(true);
        }
    }//GEN-LAST:event_kuningToolActionPerformed

    private void biruToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruToolActionPerformed
        // TODO add your handling code here:
         if(biruTool.isSelected()){
            hargaTool.setText("Rp. 200.000");
            merahTool.setEnabled(false);
            hijauTool.setEnabled(false);
            kuningTool.setEnabled(false);
        }else{
            merahTool.setEnabled(true);
            hijauTool.setEnabled(true);
            kuningTool.setEnabled(true);
        }
    }//GEN-LAST:event_biruToolActionPerformed

    private void biruObeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biruObeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biruObeActionPerformed

    private void merahObeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merahObeActionPerformed
        // TODO add your handling code here:
         if(merahObe.isSelected()){
            hargaObe.setText("Rp. 35.000");
            hijauObe.setEnabled(false);
            kuningObe.setEnabled(false);
            biruObe.setEnabled(false);
        }else{
            hijauObe.setEnabled(true);
            kuningObe.setEnabled(true);
            biruObe.setEnabled(true);
        }
    }//GEN-LAST:event_merahObeActionPerformed

    private void hijauObeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hijauObeActionPerformed
        // TODO add your handling code here:
        if(hijauObe.isSelected()){
            hargaObe.setText("Rp. 40.000");
            merahObe.setEnabled(false);
            kuningObe.setEnabled(false);
            biruObe.setEnabled(false);
        }else{
            merahObe.setEnabled(true);
            kuningObe.setEnabled(true);
            biruObe.setEnabled(true);
        }
    }//GEN-LAST:event_hijauObeActionPerformed

    private void kuningObeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuningObeActionPerformed
        // TODO add your handling code here:
        if(kuningObe.isSelected()){
            hargaObe.setText("Rp. 200.000");
            merahObe.setEnabled(false);
            hijauObe.setEnabled(false);
            biruObe.setEnabled(false);
        }else{
            merahObe.setEnabled(true);
            hijauObe.setEnabled(true);
            biruObe.setEnabled(true);
        }
    }//GEN-LAST:event_kuningObeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         b.ta("raffi mahya", "0896666823165", "jl. kutisari utara");
        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lamanTigaPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lamanTigaPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lamanTigaPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lamanTigaPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lamanTigaPer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton biruDril;
    private javax.swing.JRadioButton biruObe;
    private javax.swing.JRadioButton biruTool;
    private javax.swing.JButton deskDril;
    private javax.swing.JButton deskObe;
    private javax.swing.JButton deskTool;
    private javax.swing.JTextField hargaDril;
    private javax.swing.JTextField hargaObe;
    private javax.swing.JTextField hargaTool;
    private javax.swing.JRadioButton hijauDril;
    private javax.swing.JRadioButton hijauObe;
    private javax.swing.JRadioButton hijauTool;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jumDrillBir;
    private javax.swing.JSpinner jumDrillHij;
    private javax.swing.JSpinner jumDrillKun;
    private javax.swing.JSpinner jumDrillMer;
    private javax.swing.JSpinner jumObeBir;
    private javax.swing.JSpinner jumObeHij;
    private javax.swing.JSpinner jumObeKun;
    private javax.swing.JSpinner jumObeMer;
    private javax.swing.JSpinner jumToolBir;
    private javax.swing.JSpinner jumToolHij;
    private javax.swing.JSpinner jumToolKun;
    private javax.swing.JSpinner jumToolMer;
    private javax.swing.JRadioButton kuningDril;
    private javax.swing.JRadioButton kuningObe;
    private javax.swing.JRadioButton kuningTool;
    private javax.swing.JRadioButton merahDril;
    private javax.swing.JRadioButton merahObe;
    private javax.swing.JRadioButton merahTool;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField tfTotalPer;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JButton totalPer;
    // End of variables declaration//GEN-END:variables
    void nama(String nama1){
        nama.setText(nama1);
    }
    void totalHar(int harga1){
        totalBayar.setText(Integer.toString(harga1));
    }
}
